### ISSUE TITLE
Unsigned

### ISSUE THREAD

**Issue by neopostmodern** [michalkow/xkcd-substitutions#5]
I'd like to use this addon in FF46 but it's not signed. Disabling the signed requirement in the settings won't help for long because the setting will disappear in FF47.

**Comment by michalkow** [comment]
I don't use Firefox and I am not sure what are sign requirements in Firefox. Tried looking into the topic, but maybe you can point me into right direction. Can you provide a link to the issue?

**Comment by neopostmodern** [comment]
Oh, sorry. Reported in wrong repo, that only concerns the addon version, obviously not the bookmark version!
Keep the good work up and let's hope for more substitutions :)
